#!/usr/bin/php
<?

global $entities;
$entities = array(
	"LOD2"=>array("label"=>"LOD2 EU Project","url"=>"http://lod2.eu", "logo"=>"http://lod2.eu/BlogPost/wp-content/uploads/2010/09/lod2-logo.jpg"),
	"ACoLi"=>array("label"=>"ACoLi: Angewandte Computerlinguistik","url"=>"http://acoli.cs.uni-frankfurt.de/", "logo"=>"http://www.informatik.uni-frankfurt.de/images/logos/goethe-universitaet-logo.jpg"),
	"IMP"=>array("label"=>"Institute Mihailo Pupin","url"=>"http://www.pupin.rs/" ),
	"Zemanta"=>array("label"=>"Zemanta","url"=>"http://www.zemanta.com/" ),
	"VistaTEC"=>array("label"=>"VistaTEC","url"=>"http://vistatec.ie" ),
	"OpenLink"=>array("label"=>"OpenLink Software","url"=>"http://www.openlinksw.com/" ),
	"MLW-LT"=>array("label"=>"MultilingualWeb-LT Working Group","url"=>"http://www.w3.org/International/multilingualweb/lt/" ),
	"ULEI"=>array("label"=>"University  of Leipzig","url"=>"http://uni-leipzig.de" ),
	"KAIST"=>array("label"=>"SWRC at KAIST","url"=>"http://semanticweb.kaist.ac.kr/" ),
	"SWC"=>array("label"=>"Semantic Web Company","url"=>"http://www.semantic-web.at/" ),
	"TCD"=>array("label"=>"Trinity College Dublin","url"=>"http://www.tcd.ie" ),
	"Ontos"=>array("label"=>"Ontos","url"=>"http://www.ontos.com" ),
	"AKSW"=>array("label"=>"AKSW","url"=>"http://aksw.org" ),
//w3c
// tools
 //  "PoolParty"=>array("PoolParty"=>"http://lod2.eu"), 
 //   "COAT", "Korean NLP2RDF"
 /*   Zemanta
    DS2
    THD
    Virtuoso Sponger
    Apache Stanbol
    COAT
    SemanticQuran
    "DBpedia Spotlight", "MontyLingua"*/
// people	
	"Christian Chiarcos"=>array("label"=>"Christian Chiarcos", "url"=>"", "logo"=>""),
	"Harald Beck"=>array("label"=>"Harald Beck", "url"=>"", "logo"=>""),
	"Key-Sun Choi"=>array("label"=>"Key-Sun Choi", "url"=>"", "logo"=>""),
	"Mateja Verlic"=>array("label"=>"Harald Beck", "url"=>"", "logo"=>""),
	"Mladen Stanojevic"=>array("label"=>"Harald Beck", "url"=>"", "logo"=>""),
	"Uros Milosevic"=>array("label"=>"", "url"=>"", "logo"=>""),
	"Mitko Illiev"=>array("label"=>"", "url"=>"", "logo"=>""),
	"Ali Khalili"=>array("label"=>"Ali Khalili", "url"=>"", "logo"=>""),
	"Daniel Hladky"=>array("label"=>"Daniel Hladky", "url"=>"", "logo"=>""),
	"Phil Ritchie"=>array("label"=>"Phil Ritchie", "url"=>"", "logo"=>""),
	"Leroy Finn"=>array("label"=>"Leroy Finn", "url"=>"", "logo"=>""),
	"Felix Sasaki"=>array("label"=>"Felix Sasaki", "url"=>"", "logo"=>""),
	"Tomas Kliegr"=>array("label"=>"Tomas Kliegr", "url"=>"", "logo"=>""),
	"Rupert Westenthaler"=>array("label"=>"", "url"=>"", "logo"=>""),
	"Chris Röder"=>array("label"=>"Chris Röder", "url"=>"", "logo"=>""),
	"Artjom Klein"=>array("label"=>"Artjom Klein", "url"=>"", "logo"=>""),
	"Tadej Stainer"=>array("label"=>"Tadej Stainer", "url"=>"", "logo"=>""),
	"Marcus Nitzschke"=>array("label"=>"Marcus Nitzschke", "url"=>"", "logo"=>""),
	"Mohamed Sherif"=>array("label"=>"Mohamed Sherif", "url"=>"", "logo"=>""),
	"Sebastian Lippert"=>array("label"=>"Sebastian Lippert", "url"=>"", "logo"=>""),
	"Daniel Gerber"=>array("label"=>"Daniel Gerber", "url"=>"", "logo"=>""),
	"Markus Ackermann"=>array("label"=>"Markus Ackermann", "url"=>"", "logo"=>""),
	"Martin Brümmer"=>array("label"=>"Martin Brümmer", "url"=>"", "logo"=>""),
	""=>array("label"=>"", "url"=>"", "logo"=>""),
	""=>array("label"=>"", "url"=>"", "logo"=>""),
	""=>array("label"=>"", "url"=>"", "logo"=>"")
	//V UK + MIRKO
	);

//http://ubo.openphacts.org/index.php?id=4684
//LINGPIPE





function r($id, $logo=true){
	global $entities;
	if(!isset($entities[$id]) || empty($entities[$id])  ){
		die ("$id not found: ".$entities[$id]);
		}
	$entity = $entities[$id];
	if(isset($entity ['url'] ) && !empty($entity ['url']) ){
		if ($logo && isset($entity ['logo']) && ! empty($entity ['logo'])){
			$anchor = "<img src=\"".$entity['logo']."\" title=\"".$entity['label']."\" />";
		}else if(isset($entity ['label']) && !empty($entity ['label'])) {
			$anchor = $entity['label'];
			$label = $entity['label'];
		}else{
			$anchor = $id;
			$label = $id;
		}
		echo '<a href="'.$entity ['url'].'" target="_blank">'.$anchor.'</a>, ';
		}
	else {
		echo $entity['label'];
	}	
	

	
}


?>
<ul>
<li><?=r("Christian Chiarcos")?></li>
</ul>
